theme_background = "#{{colors.base.default.hex}}"
theme_main_fg = "#{{colors.on_surface.default.hex}}"
theme_title = "#{{colors.primary.default.hex}}"
theme_hi_fg = "#{{colors.secondary.default.hex}}"
theme_selected_bg = "#{{colors.primary_container.default.hex}}"
theme_selected_fg = "#{{colors.on_primary_container.default.hex}}"
theme_graph_bg = "#{{colors.surface_variant.default.hex}}"

theme_cpu_color_1 = "#{{colors.green.default.hex}}"
theme_cpu_color_2 = "#{{colors.green.default.hex}}"
theme_cpu_color_3 = "#{{colors.teal.default.hex}}"
theme_cpu_color_4 = "#{{colors.teal.default.hex}}"
theme_cpu_color_5 = "#{{colors.yellow.default.hex}}"
theme_cpu_color_6 = "#{{colors.yellow.default.hex}}"
theme_cpu_color_7 = "#{{colors.peach.default.hex}}"
theme_cpu_color_8 = "#{{colors.peach.default.hex}}"
theme_cpu_color_9 = "#{{colors.red.default.hex}}"
theme_cpu_color_10 = "#{{colors.red.default.hex}}"

theme_mem_color_1 = "#{{colors.green.default.hex}}"
theme_mem_color_2 = "#{{colors.green.default.hex}}"
theme_mem_color_3 = "#{{colors.teal.default.hex}}"
theme_mem_color_4 = "#{{colors.teal.default.hex}}"
theme_mem_color_5 = "#{{colors.yellow.default.hex}}"
theme_mem_color_6 = "#{{colors.yellow.default.hex}}"
theme_mem_color_7 = "#{{colors.peach.default.hex}}"
theme_mem_color_8 = "#{{colors.peach.default.hex}}"
theme_mem_color_9 = "#{{colors.red.default.hex}}"
theme_mem_color_10 = "#{{colors.red.default.hex}}"

theme_proc_color_1 = "#{{colors.green.default.hex}}"
theme_proc_color_2 = "#{{colors.green.default.hex}}"
theme_proc_color_3 = "#{{colors.teal.default.hex}}"
theme_proc_color_4 = "#{{colors.teal.default.hex}}"
theme_proc_color_5 = "#{{colors.yellow.default.hex}}"
theme_proc_color_6 = "#{{colors.yellow.default.hex}}"
theme_proc_color_7 = "#{{colors.peach.default.hex}}"
theme_proc_color_8 = "#{{colors.peach.default.hex}}"
theme_proc_color_9 = "#{{colors.red.default.hex}}"
theme_proc_color_10 = "#{{colors.red.default.hex}}"
