# =============================================================================
# cava/config — Automatisch gegenereerd door matugen. Pas dit bestand NIET aan.
# Gradient: accent 1 (focus) → accent 2 (energie) → accent 3 (piek).
# =============================================================================

[general]
mode = normal
framerate = 60
autosens = 1
sensitivity = 100
bars = 0
bar_width = 2
bar_spacing = 1
bar_height = 32
channels = stereo
sleep_timer = 0

[input]
method = pipewire
source = auto

[output]
method = ncurses
raw_target = /dev/stdout
data_format = binary
bit_format = 16bit
ascii_max_range = 1000
alsa_hint = default

[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '{{colors.primary_container.default.hex}}'
gradient_color_2 = '{{colors.primary.default.hex}}'
gradient_color_3 = '{{colors.secondary_accent_container.default.hex}}'
gradient_color_4 = '{{colors.secondary_accent.default.hex}}'
gradient_color_5 = '{{colors.tertiary_accent_container.default.hex}}'
gradient_color_6 = '{{colors.tertiary_accent.default.hex}}'
gradient_color_7 = '{{colors.inverse_primary.default.hex}}'
gradient_color_8 = '{{colors.error.default.hex}}'

background = '{{colors.background.default.hex}}'

[smoothing]
monstercat = 0
waves = 0
gravity = 100
ignore_le = 0

[eq]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
