-- Generated by Matugen. Do not edit: kingstra-matugen-run replaces this file.
local M = {}

function M.apply()
    hl.config({
        general = {
            col = {
                active_border = {
                    colors = {
                        "rgba({{colors.primary.default.hex_stripped}}ee)",
                        "rgba({{colors.secondary_accent_source.default.hex_stripped}}ee)",
                        "rgba({{colors.tertiary_accent_source.default.hex_stripped}}ee)",
                    },
                    angle = 55,
                },
                -- A defined inactive contour: muted, never invisible.
                inactive_border = "rgba({{colors.outline.default.hex_stripped}}99)",
            },
        },
        decoration = {
            shadow = { color = "rgba(000000cc)" },
        },
    })
end

return M
