; Automatisch gegenereerd door matugen. Pas dit bestand NIET aan.
[Matugen]
text               = {{colors.on_surface.default.hex}}
subtext            = {{colors.on_surface_variant.default.hex}}
main               = {{colors.background.default.hex}}
main-elevated      = {{colors.surface.default.hex}}
highlight          = {{colors.surface_container_high.default.hex}}
highlight-elevated = {{colors.surface_container_high.default.hex}}
sidebar            = {{colors.surface.default.hex}}
player             = {{colors.surface_container.default.hex}}
card               = {{colors.surface_container.default.hex}}
shadow             = {{colors.shadow.default.hex}}
selected-row       = {{colors.primary_container.default.hex}}
button             = {{colors.primary.default.hex}}
button-active      = {{colors.primary_container.default.hex}}
button-disabled    = {{colors.surface_variant.default.hex}}
tab-active         = {{colors.surface_container.default.hex}}
notification       = {{colors.primary.default.hex}}
notification-error = {{colors.error.default.hex}}
misc               = {{colors.primary.default.hex}}
