# =============================================================================
# 30-general.conf — Algemene lay-out en borders
# =============================================================================

general {
    gaps_in  = 4
    gaps_out = 8

    border_size = 2
    col.active_border   = $border_active
    col.inactive_border = $border_inactive

    resize_on_border         = true
    extend_border_grab_area  = 20
    hover_icon_on_border     = true

    layout = dwindle
    allow_tearing = false
}

dwindle {
    pseudotile          = true
    preserve_split      = true
    smart_split         = false
    smart_resizing      = true
    force_split         = 0       # 0 = op basis van cursor-positie
    split_width_multiplier = 1.0
}

master {
    new_status        = slave
    new_on_top        = false
    mfact             = 0.55
    orientation       = left
}

misc {
    disable_hyprland_logo   = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    vfr                     = true   # Variable Framerate — bespaart CPU
    vrr                     = 0      # VRR/G-Sync: 0=uit, 1=aan, 2=alleen fullscreen
    key_press_enables_dpms  = true
    mouse_move_enables_dpms = true
    new_window_takes_over_fullscreen = 2
    font_family             = Fira Sans
    focus_on_activate       = false
    animate_manual_resizes  = false
    enable_swallow          = false
}
