# =============================================================================
# 74-input-settings.conf — Input overrides
# =============================================================================
# Aangepast via de Settings-popup.
# =============================================================================

input {
    kb_layout = us
    kb_options =

    touchpad {
        # false = button areas (Windows-achtig), true = clickfinger gedrag
        clickfinger_behavior = false
    }
}
