# =============================================================================
# hypr-colors.conf — Matugen template voor Hyprland kleuren
# Gegenereerd door: matugen image <wallpaper>
# =============================================================================

$primary           = rgba(a9cdd6ee)
$on_primary        = rgba(10353cee)
$primary_container = rgba(3c5e66ee)
$secondary         = rgba(bbc9cdee)
$on_secondary      = rgba(263236ee)
$surface           = rgba(121414ee)
$on_surface        = rgba(e3e2e2ee)
$background        = rgba(121414ff)
$error             = rgba(ffb4abee)

$border_active   = $primary $secondary 45deg
$border_inactive = rgba(8b929444)
$shadow_color    = rgba(000000cc)
