# =============================================================================
# kitty-colors.conf — Matugen template voor Kitty
# =============================================================================

foreground           #e3e2e2
background           #121414
selection_foreground #10353c
selection_background #a9cdd6

cursor               #a9cdd6
cursor_text_color    #10353c

url_color            #eabe9c

active_border_color   #a9cdd6
inactive_border_color #8b9294
bell_border_color     #ffb4ab

active_tab_foreground   #10353c
active_tab_background   #a9cdd6
inactive_tab_foreground #e3e2e2
inactive_tab_background #41484a
tab_bar_background      #121414

color0  #000000
color1  #ffb4ab
color2  #eabe9c
color3  #bbc9cd
color4  #a9cdd6
color5  #ffffff
color6  #735237
color7  #e3e2e2
color8  #8b9294
color9  #ffb4ab
color10 #eabe9c
color11 #bbc9cd
color12 #a9cdd6
color13 #ffffff
color14 #735237
color15 #41484a
