foreground            #e3e2e2
background            #121414
selection_foreground  #10353c
selection_background  #a9cdd6
url_color             #eabe9c
cursor                #a9cdd6
cursor_text_color     #10353c

color0   #121414
color1   #ffb4ab
color2   #a9cdd6
color3   #eabe9c
color4   #a9cdd6
color5   #eabe9c
color6   #735237
color7   #e3e2e2

color8   #8b9294
color9   #ffb4ab
color10  #a9cdd6
color11  #eabe9c
color12  #a9cdd6
color13  #eabe9c
color14  #735237
color15  #e3e2e2

tab_bar_background              #121414
tab_bar_margin_color            #121414
active_tab_foreground           #10353c
active_tab_background           #a9cdd6
inactive_tab_foreground         #c1c8ca
inactive_tab_background         #121414
