[meta]
name = "Dark"
description = "Diep en donker, hoog contrast"
icon = "󰖔"
preview_image = "dark.jpg"

[matugen]
scheme_type = "scheme-content"
color_index = 0
contrast = -0.2

[appearance]
border_radius = 10
border_width = 2
gaps_in = 4
gaps_out = 8
bar_opacity = 0.80
popup_opacity = 0.88
blur_size = 6
blur_passes = 2
animation_speed = 1.0

[fonts]
ui_font = "Inter"
ui_font_size = 13
mono_font = "JetBrainsMono Nerd Font"
mono_font_size = 12

[icons]
icon_theme = "Papirus-Dark"

[quickshell]
bar_height = 34
bar_position = "top"
