[meta]
name = "Rocky"
description = "Graniet — hoekig, solide, geen nonsens"
icon = "󰋘"
preview_image = "rocky.jpg"

[matugen]
scheme_type = "scheme-monochrome"
color_index = 0
contrast = 0.0
mode = "dark"

[appearance]
border_radius = 2
border_width = 4
gaps_in = 2
gaps_out = 4
bar_opacity = 0.98
popup_opacity = 0.98
blur_size = 2
blur_passes = 1
animation_speed = 1.4

[fonts]
ui_font = "JetBrains Mono"
ui_font_size = 12
mono_font = "JetBrainsMono Nerd Font"
mono_font_size = 12

[icons]
icon_theme = "Breeze"

[quickshell]
bar_height = 32
bar_position = "top"
