[meta]
name = "Rocky"
description = "Ruig en industrieel, neutrale steentinten"
icon = "󰋘"
preview_image = "rocky.jpg"

[matugen]
scheme_type = "scheme-monochrome"
color_index = 0
contrast = 0.0

[appearance]
border_radius = 4
border_width = 3
gaps_in = 2
gaps_out = 4
bar_opacity = 0.80
popup_opacity = 0.88
blur_size = 3
blur_passes = 1
animation_speed = 1.3

[fonts]
ui_font = "Inter"
ui_font_size = 13
mono_font = "JetBrainsMono Nerd Font"
mono_font_size = 12

[icons]
icon_theme = "Papirus-Dark"

[quickshell]
bar_height = 34
bar_position = "top"
